id: DE1474FFD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:31:43+00:00'
last_modified: '2022-05-26T12:43:19.362271+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    bdb5:
      image_group_id: I1PD95883
      title: འཕགས་མ་རིག་པ་ཆེན་མོ་སོ་སོར་འབྲང་མའི་འཁོར་ལོ།
      total_pages: 1044
      order: 38
      base_file: bdb5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
