id: 88eb11444e474d328cc75f5337eff7ee
initial_creation_type: ocr
source_metadata:
  volumes:
    aa7e1734286e4377b8a0db1f13dcfe7a:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་མ་རིག་པ་ཆེན་མོ་སོ་སོར་འབྲང་མའི་འཁོར་ལོ།
      total_pages: 1044
      volume_number: 38
